[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
providers = ["nodejs"]

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "${{PORT}}"

[services.api]
regions = ["us-west1"]
scaling = { minReplicas = 1, maxReplicas = 3 }

[networking]
servicePort = 3001
externalPort = 443
serviceDomain = "finviz-api"